#!/bin/bash

if test type vim >/dev/null 2>&1; then
    echo "vim isn't installed. Skipping."
    exit 1
fi

PLUG_FILE="$HOME/.vim/autoload/plug.vim"

if [[ ! -f "$PLUG_FILE" ]]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/ideavimrc" "$HOME/.ideavimrc"

#vim -c "PlugInstall"
