---
- name: Install go
  import_tasks: linux.yml
  when: ansible_distribution != "MacOSX"

- name: Install go
  community.general.homebrew:
      name: go
      state: present
  when: ansible_distribution == "MacOSX"

- name: Install keg binary
  command: "{{ go_bin[ansible_distribution] }} install github.com/rwxrob/keg/cmd/keg@latest"
  args:
      creates: "{{ gobin }}/keg"

- name: Install gocomplete binary
  command: "{{ go_bin[ansible_distribution] }} install github.com/posener/complete/gocomplete@latest"
  args:
      creates: "{{ gobin }}/gocomplete"

- name: Install gopls binary
  command: "{{ go_bin[ansible_distribution] }} install golang.org/x/tools/gopls@latest"
  args:
      creates: "{{ gobin }}/gopls"

- name: Install hugo binary
  command: "{{ go_bin[ansible_distribution] }} install github.com/gohugoio/hugo@latest"
  args:
      creates: "{{ gobin }}/hugo"

- name: Install auth binary
  command: "{{ go_bin[ansible_distribution] }} install github.com/rwxrob/auth-go/cmd/auth@latest"
  args:
      creates: "{{ gobin }}/auth"
