repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.2
    hooks:
      - id: stylua

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
