#!/bin/bash

set -e

_log() {
    echo "Running: $*"
    exec "$@"
}

_have() { type "$1" &>/dev/null; }

# if [[ "$(uname -r)" =~ Darwin ]]; then
#     if ! _have brew; then
#         _log /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#     fi
#     if ! _have python3; then
#         _log /opt/homebrew/bin/brew install python3
#     fi
# fi

if _have pip3; then
    PIP=pip3
elif _have pip; then
    PIP=pip
else
    _log "pip not found. Please install manually"
    exit 1
fi

if ! _have ansible; then
    _log "$PIP" install --user ansible argcomplete
fi

_log ansible-galaxy collection install -r requirements.yml
