#!/usr/bin/env bash
set -e

if ! command -v python3 &>/dev/null; then
    echo "Installing ansible dependencies"
    sudo apt install -y python3 python3-pip
fi
 
if ! command -v ansible &>/dev/null; then
    echo "Install ansible and tools"
    python3 -m pip install --user argcomplete
    python3 -m pip install --user ansible
fi
