#!/usr/bin/env bash
set -e

VERSION="$(nvim -v | grep "NVIM" | cut -d' ' -f2 | sed 's/v//g')"
# MAJOR=$(echo "${VERSION}" | cut -d'.' -f1)
MINOR=$(echo "${VERSION}" | cut -d'.' -f2)
# PATCH="$(echo "${VERSION}" | cut -d'.' -f3)

if [ "${MINOR}" -le 9 ]; then
    sudo add-apt-repository ppa:neovim-ppa/unstable -y
    sudo apt-get install -y neovim
fi

if command -v npm &>/dev/null && ! command -v prettier &>/dev/null; then
    npm i -g prettier
    exit
fi
