#!/usr/bin/env bash
set -e

# This needs to be first
./install-base
./install-fnm
./install-zsh

# These are all independent
./install-gh
./install-git
./install-go
./install-neovim
./install-pandoc
./install-podman
./install-rust
