#!/usr/bin/bash

set -e
VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
curl -sSLO "https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl"
curl -sSLO "https://dl.k8s.io/${VERSION}/bin/linux/amd64/kubectl.sha256"
echo "$(head -1 kubectl.sha256) kubectl" | sha256sum --check
sudo mv kubectl /usr/local/bin && sudo chmod +x /usr/local/bin/kubectl
rm kubectl.sha256
