#!/bin/bash

set -e

# Ensure zsh is installed
if ! command -v zsh &>/dev/null; then
    echo sudo apt update
    echo sudo apt install -y zsh
fi

# Install oh my zsh if it is not already
DEFAULT="${XDG_DATA_HOME:-$HOME/.local/share/oh-my-zsh}"
ZSH="${ZSH:-$DEFAULT}"
if [[ ! -d "$ZSH" ]]; then
    # sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    git clone https://github.com/ohmyzsh/ohmyzsh "$ZSH"
fi


# Set the current shell to zsh
CURRENT_SHELL=$(grep "${USER}" /etc/passwd | awk -F':' '{print $7}')
if [[ ! "$CURRENT_SHELL" =~ "zsh" ]]; then
    chsh -s "$(which zsh)"
   # assume Zsh
fi
