#!/usr/bin/env bash

VERSION=$(podman version | grep '^Version' | awk '{print $2}')
MAJOR=$(echo "${VERSION}" | cut -d'.' -f1)
MINOR=$(echo "${VERSION}" | cut -d'.' -f2)
if [ "$MAJOR" -ge 4 ] && [ "$MINOR" -ge 4 ]; then
    exit
fi

sudo mkdir -p /etc/apt/keyrings

# Debian Testing/Bookworm
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/Release.key |
    gpg --dearmor |
    sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg >/dev/null
echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
    https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/ /" |
    sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list >/dev/null

# Debian Unstable/Sid
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/Release.key |
    gpg --dearmor |
    sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg >/dev/null
echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
    https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/ /" |
    sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list >/dev/null

# Install Podman
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install podman buildah docker-compose netavark
