#!/usr/bin/env bash
set -e

if command -v fnm &>/dev/null; then
    exit
fi

FNM_DIR="fnm"
INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/${FNM_DIR}"
curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "$INSTALL_DIR" --skip-shell

fnm install 18 &>/dev/null
