#!/bin/sh

RG_PREFIX="rg --files-with-matches --ignore-case"
INITIAL_QUERY=""
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'"
CHOICE=$(fzf --bind "change:reload:$RG_PREFIX {q} || true" \
    --sort \
    --multi \
    --preview "[[ ! -z {} ]] && $VISUAL {q} {}" \
    --ansi --phony --query "$INITIAL_QUERY")

# --preview '[[ ! -z {} ]] && rg --pretty --ignore-case --context 5 {q} {}' \
if [ -n "$CHOICE" ]; then
    $EDITOR "$CHOICE"
    echo "$CHOICE"
fi
