---
- name: Install and/or upgrade spacemacs
  git:
      repo: https://github.com/syl20bnr/spacemacs.git
      dest: "~/.emacs"
      version: "develop"
      update: yes

- name: Install emacs dotfiles
  template:
      src: dot_spacemacs.j2
      dest: "~/.spacemacs"
      mode: "644"
