---
- name: Download Go tarball
  get_url:
      url: "https://golang.org/dl/{{ go_tarball }}"
      dest: "~/.local/src/{{ go_tarball }}"
      checksum: "{{ go_checksum }}"

- name: Register current Go version (if any)
  command: "{{ data_dir }}/go/bin/go version"
  ignore_errors: yes
  failed_when: false
  changed_when: false
  register: go_version

- name: DEBUG
  debug:
      msg: "{{ go_version }}"

- name: Remove old installation of go
  file:
      path: "{{ data_dir }}/go"
      state: absent
  when: go_version.rc == 0 and go_version.stdout != go_version_check

- name: Create go root directory
  file:
      path: "{{ data_dir }}/go"
      state: directory

- name: Extract Go tarball
  unarchive:
      src: "{{ data_dir }}/src/{{ go_tarball }}"
      dest: "{{ data_dir }}"
      copy: no
  when: go_version != 0 or go_version.stdout != go_version_check

- name: Create ~/.local/bin directory
  file:
      path: ~/.local/bin
      state: directory

- name: "Link go binary to {{ data_dir }}/bin/go"
  file:
      src: "{{ data_dir }}/go/bin/go"
      dest: ~/.local/bin/go
      state: link
