- import_tasks: misc.yml

- import_tasks: zsh.yml
  when: install_zsh
  tags:
      - zsh

- import_tasks: vim.yml
  when: install_vim
  tags:
      - vim

- import_tasks: emacs.yml
  when: install_emacs
  tags:
      - emacs

- import_tasks: javascript.yml
  when: install_javascript
  tags:
      - javascript
