---
- name: Create required directories
  become: yes
  become_user: "{{ dotfiles_user }}"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ data_dir }}"
    - "~/.local/bin"
    - "{{ config_dir }}"

- name: Install useful scripts
  become: yes
  become_user: "{{ dotfiles_user }}"
  copy:
    src: dot_local/bin/
    dest: ~/.local/bin/
    mode: +x
  tags:
    - scripts

- name: "Install misc dotfiles"
  become: yes
  become_user: "{{ dotfiles_user }}"
  copy:
    src: "dot_{{ item }}"
    dest: "~/.{{ item }}"
  loop:
    - gitconfig
    - Xdefaults

- import_tasks: zsh.yml
  when: install_zsh
  tags:
    - zsh

- import_tasks: vim.yml
  when: install_vim
  tags:
    - vim

- import_tasks: nvim.yml
  when: install_nvim
  tags:
    - nvim

- import_tasks: emacs.yml
  when: install_emacs
  tags:
    - emacs
