---
- name: Create required directories
  file:
      path: "{{ item }}"
      state: directory
  loop:
      - "{{ data_dir }}"
      - "~/.local/bin"
      - "~/.local/src"
      - "{{ config_dir }}"
      - "{{ config_dir }}/alacritty"

- name: Install useful scripts
  copy:
      src: dot_local/bin/
      dest: ~/.local/bin/
      mode: +x
  tags:
      - scripts

- name: "Install misc dotfiles"
  template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "644"
  with_items:
      - src: "dot_gitconfig.j2"
        dest: "~/.gitconfig"
      - src: "dot_Xdefaults.j2"
        dest: "~/.Xdefaults"
      - src: "alacritty.yml.j2"
        dest: "{{ config_dir }}/alacritty/alacritty.yml"
