---
- name: Create nvim config directory
  file:
      path: "{{ config_dir }}/nvim"
      state: directory

- name: Install nvim dotfiles
  copy:
      src: dot_vimrc
      dest: "{{ config_dir }}/nvim/init.vim"

- name: Install and/or update vundle
  git:
      repo: "https://github.com/VundleVim/Vundle.vim.git"
      dest: "{{ config_dir }}/nvim/bundle/Vundle.vim"
      update: yes

- name: Install and/or update srcery-vim
  git:
      repo: https://github.com/srcery-colors/srcery-vim
      dest: "{{ config_dir }}/nvim/plug/default/opt"

- name: Check if nvim is installed
  command: which nvim
  register: nvim_bin
  changed_when: false

- name: Install nvim plugins
  command:
      cmd: "nvim +PluginInstall +qall"
  changed_when: false # FIXME: changed when vim actually updates/install packages; not worth the effort
  when: nvim_bin.rc == 0
