---
- name: "Create neovim config directory"
  file:
      path: "{{ config_dir }}/nvim"
      state: directory

- name: "Install dotfiles for vim and neovim"
  template:
      src: dot_vimrc.j2
      dest: "{{ item.vim_dotfile }}"
      mode: "644"
  with_items:
      - vim_dotfile: "~/.vimrc"
        vim_config_dir: "~/.vim"
      - vim_dotfile: "{{ config_dir }}/nvim/init.vim"
        vim_config_dir: "{{ config_dir }}/nvim"

- name: Create plugin directories
  file:
      path: "{{ item }}"
      state: directory
  loop:
      - "~/.vim/autoload"
      - "{{ config_dir }}/nvim/autoload"

- name: Download vim-plug for vim and neovim
  get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ item }}/autoload/plug.vim"
      mode: "644"
  loop:
      - "~/.vim"
      - "{{ config_dir }}/nvim"
