".local/share/oh-my-zsh":
  type: "git-repo"
  url: "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod: "168h"

".tmux/plugins/tpm":
  type: "git-repo"
  url: "https://github.com/tmux-plugins/tpm"
  refreshPeriod: "168h"
