export DOTFILES=$HOME/.dotfiles
export GOPATH=~/Devel/gocode
export ANDROID_HOME=/opt/android-sdk
export PYENV_ROOT="$HOME/.pyenv"
export CARGO_HOME=$HOME/.cargo
export RUST_SRC_PATH=$HOME/.local/src/rust/src

if [[ "$SHLVL" -eq 4 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprofile"
fi
