export DOTFILES=$HOME/.dotfiles
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export TERM=xterm

eval $(dircolors ~/.dircolors)

if [[ "$SHLVL" -eq 4 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

