# Path to your oh-my-zsh installation.
export ZSH=/home/raviko/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this
# to "random" it'll load a random theme each time that
# oh-my-zsh is loaded.  See
# https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="jlrickert"

# Uncomment the following line to use case-sensitive
# completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive
# completion. Case sensitive completion must be off. _ and -
# will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly
# auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to
# auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting
# terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command
# auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst
# waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable
# marking untracked files under VCS as dirty. This makes
# repository status check for large repositories much, much
# faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the
# command execution time stamp shown in the history command
# output.  The optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than
# $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be
# found in ~/.oh-my-zsh/plugins/*) Custom plugins may be
# added to ~/.oh-my-zsh/custom/plugins/ Example format:
# plugins=(rails git textmate ruby lighthouse) Add wisely,
# as too many plugins slow down shell startup.
plugins=(
    autopep8
    cabal
    catimg
    common-aliases
    django
    docker
    emacs
    encode64
    fasd
    gem
    git
    jsontools
    lein
    pep8
    per-directory-history
    pip
    pyenv
    pylint
    python
    rails
    rake
    rbenv
    ruby
    rust
    systemd
    vagrant
    vi-mode
    web-search
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

################################################################################
### User configuration
################################################################################
# Environmental variables
export DEFAULT_USER=`whoami`
export DOTFILES=$HOME/.dotfiles
export GOPATH=$HOME/Development/gocode
export ANDROID_HOME=/opt/android-sdk
export PYENV_ROOT=$HOME/.pyenv
export CARGO_HOME=$HOME/.cargo
export RUST_SRC_PATH=$HOME/.local/src/rust/src
export LANG=en_US.UTF-8
export BROWSER=firefox
export EDITOR=vim
export VISUAL=vim
export PAGER=less
export RUBYLIB=$HOME/.local/lib/ruby
export PYTHONPATH=$HOME/.local/lib/python
export PERL5LIB="/home/raviko/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
export PERL_LOCAL_LIB_ROOT="/home/raviko/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
export PERL_MB_OPT="--install_base \"/home/raviko/perl5\""
export PERL_MM_OPT="INSTALL_BASE=/home/raviko/perl5"

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

### Make sure a tmp dir exists
if [[ ! -d "$TMPDIR" ]]; then
    export TMPDIR="/tmp/$USER"
    mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

################################################################################
### Paths
################################################################################
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

path=(
    $HOME/perl5/bin
    $path[@]
    $HOME/.local/bin
    $PYENV_ROOT/bin
    $HOME/.cargo/bin
    $GOPATH/bin
)

# Set the list were completions are stored
fpath=(
    $fpath[@]
    $HOME/.local/share/completions
)

# Set the the list of directories that cd searches.
cdpath=(
    $cdpath
)

# Load my custom functions

for each in ~/.local/lib/zsh/*.zsh; do
    source $each
done

################################################################################
### Aliass
################################################################################
alias py='python'
alias py2='python2'
alias rb='ruby'
alias wo='fire_fox_open'

alias emacs='$EMACS_PLUGIN_LAUNCHER --no-wait --create-frame'
alias e='$EMACS_PLUGIN_LAUNCHER --no-wait'

alias pac='pacman --color auto'
alias paci='sudo pacman --color auto --sync'
alias pacI='sudo pacman --color auto --upgrades'
alias pacu='sudo pacman --color auto --sync --refresh && sudo abs'
alias pacU='sudo pacman --color auto --sync --refresh --sysupgrade'
alias pacx='sudo pacman --color auto --remove'
alias pacX='sudo pacman --color auto --remove --nosave --recursive'
alias pacs='pacman --color auto --sync --search'
alias pacq='pacman --color auto --query --info'
alias pacQ='pacman --color auto --query --search'
alias paclsorphans='sudo pacman --color auto  -Qdt'
alias pacxmorphans='sudo pacman --color auto  -Rs $(pacman -Qtdq)'

alias yac='yaourt --color auto'
alias yaci='yaourt --color auto --sync'
alias yacI='yaourt --color auto --upgrades'
alias yacu='yaourt --color auto --sync --refresh && sudo abs'
alias yacU='yaourt --color auto --sync --refresh --sysupgrade --aur'
alias yacx='yaourt --color auto --remove'
alias yacX='yaourt --color auto --remove --nosave --recursive'
alias yacs='yaourt --color auto --sync --search'
alias yacq='yaourt --color auto --query --info'
alias yacQ='yaourt --color auto --query --search'
alias yaclsorphans='sudo yaourt --color auto -Qdt'
alias yacxmorphans='sudo yaourt --color auto -Rs $(pacman -Qtdq)'

#### miscilaneas
alias screenshot="maim ~/Media/Screenshots/$(date +%F-%T).png"
alias snapterm="maim -i $(xdotool getactivewindow) ~/Media/Screenshots/$(date +%F-%T).png"
alias df="df -h"

################################################################################
### Keymap
################################################################################
bindkey '^[n' down-history
bindkey '^[p' up-history
bindkey '^[r' history-incremental-search-backward
bindkey -M vicmd "w" vi-backward-word
bindkey -M vicmd "e" vi-forward-word-end
bindkey -M vicmd '^[n' down-history
bindkey -M vicmd '^[p' up-history
bindkey -M vicmd 'k' up-line
bindkey -M vicmd 'j' down-line
export KEYTIMEOUT=1
