---
# - name: Install golang
#   become: yes
#   ansible.builtin.unarchive:
#     src: 
#     dest: /usr/local
#     remote_src: yes

- name: Download Go archive
  ansible.builtin.get_url:
    url: "https://go.dev/dl/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz"
    dest: "/tmp/go{{ go_version }}.tar.gz"
    checksum: "{{ go_checksum }}"

- name: Extract Go archive
  ansible.builtin.unarchive:
    src: "/tmp/go{{ go_version }}.tar.gz"
    dest: "{{ go_install_dir }}"
    remote_src: yes
    creates: "{{ go_install_dir }}/go"

