#!/bin/bash

NVIM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
NVIM_BAK="${XDG_CONFIG_HOME:-$HOME/.config}/nvim.bak"

DIR="$(dirname $NVIM_CONFIG)"
[[ ! -d "$DIR" ]] && echo mkdir -p "$DIR"
[[ -L $NVIM_CONFIG ]] && rm "$NVIM_CONFIG"
[[ -d $NVIM_CONFIG ]] && mv "$NVIM_CONFIG" "$NVIM_BAK"
ln -sf "$PWD/nvim" "$NVIM_CONFIG"

