#!/usr/bin/bash
set -e

if [[ -z "$NVM_DIR" ]]; then
    echo "NVM_DIR is not set"
    exit 1
fi

test ! -d $NVM_DIR && git clone https://github.com/nvm-sh/nvm $NVM_DIR

(
    cd $NVM_DIR
    git fetch --tags origin
    git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
) && \. "$NVM_DIR/nvm.sh"

