#!/usr/bin/env bash
set -e

sudo apt-get update
sudo apt-get install -y \
        apt-utils \
        build-essential \
        software-properties-common \
        apt-transport-https \
        ca-certificates \
        man-db \
        curl 

sudo apt-get install -y --no-install-recommends \
        vim tmux dialog perl python3 git gh jq sudo lynx shellcheck \
        figlet tree nmap ed bc iputils-ping bind9-dnsutils btop htop \
        libncurses5 libcurses-perl net-tools ssh sshpass sshfs rsync \
        cifs-utils smbclient bash-completion make wget less lolcat \
        silversearcher-ag ripgrep fzf direnv zsh

