---
- name: Install fnm
  shell: curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/fnm"

- name: Install Node.js
  command: "{{ ansible_env.HOME }}/.local/share/fnm/fnm install --lts"
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/fnm/aliases/lts-latest"

- name: Install Node.js packages
  command: "{{ ansible_env.HOME }}/.local/share/fnm/aliases/lts-latest/bin/npm i -g {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/fnm/aliases/lts-latest/bin/{{ item }}"
  loop: "{{ node_packages }}"

