#!/bin/bash

set -o errexit  # exit if non-zero status code is returned
set -o nounset  # exit if undefined variable is used
set -o pipefail # exit if no-zero status code is returned in a pipeline
IFS=$'\n\t'

cd $(mktemp -d)
curl -fsSL -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.7.12-stable.tar.xz
tar xf flutter_linux_3.7.12-stable.tar.xz
mv flutter "$HOME/.local/share/flutter"
flutter config --no-analytics
flutter precache
