#!/usr/bin/env bash

# Get the directory where the script is located
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
PROJECT_ROOT=$(dirname "${SCRIPT_DIR}")

if [[ ! -x ~/.local/bin/chezmoi ]]; then
	sh -c "$(curl -fsLS get.chezmoi.io/lb)"
fi

~/.local/bin/chezmoi --source "${PROJECT_ROOT}" "$@"
