#!/bin/bash

echo $0 $1
if [[ -z "$1" ]]; then
    echo "Usage:"
    echo -e "\t$0 your file name"
    exit
fi

SCRIPT=$(cat <<-EOF
#!/bin/bash

set -o errexit  # exit if non-zero status code is returned
set -o nounset  # exit if undefined variable is used
set -o pipefail # exit if no-zero status code is returned in a pipeline
IFS=$'\\\n\\\t'
EOF
)

echo -e "$SCRIPT" > "$1"
chmod +x "$1"
