#!/bin/sh

RG_PREFIX="rg --files-with-matches"
INITIAL_QUERY=""
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'"
CHOICE=$(fzf --bind "change:reload:$RG_PREFIX {q} || true" \
    --sort \
    --multi \
    --ignore-case \
    --glob "*.md" \
    --preview '[[ ! -z {} ]] && rg --pretty --context 5 {q} {}' \
    --ansi --phony --query "$INITIAL_QUERY")

[ -n "$CHOICE" ] && nvim "$CHOICE"
