#!/bin/bash
export KEG_CURRENT="${HOME}/personal/zettel"

if test -n "${COMP_LINE}"; then
    pre="${COMP_LINE#* }"
    COMP_LINE="ku ${pre}" ku
    exit 0
fi

cd "${HOME}/personal/zettel" || exit 1
ku "$@"
