#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Usage:"
    echo -e "\t$0 your file name"
    exit
fi

SCRIPT=$(cat <<-EOF
#!/usr/bin/env bash

set -o errexit  # exit if non-zero status code is returned
set -o nounset  # exit if undefined variable is used
set -o pipefail # exit if no-zero status code is returned in a pipeline
IFS=$'\\\n\\\t'

declare NOCOLOR=
[[ -t 1 ]] || NOCOLOR=y
declare GOLD=$'\033[38;2;184;138;0m'
declare RED=$'\033[38;2;255;0;0m'
declare GREY=$'\033[38;2;100;100;100m'
declare CYAN=$'\033[38;2;0;255;255m'
declare GREEN=$'\033[38;2;0;255;0m'
declare RESET=$'\033[0m'

if [[ -n "$NOCOLOR" ]] ; then
  GOLD=
  RED=
  GREY=
  CYAN=
  GREEN=
  RESET=
fi

_log() {
    local MSG="\$1"
    shift
    echo "\${GREEN}\${MSG}:\${RESET} \$@"
    "\$@"
}

_sudo() {
    if [[ "\$(whoami)" = "root" ]]; then
        "\$@"
    else
        sudo "\$@"
    fi
}


if test -n "\${COMP_LINE}"; then
	pre="\${COMP_LINE##* }"
	for c in \${cmds:+\${cmds} dev prod}; do
		test -z "\${pre}" -o "\${c}" != "\${c#"\${pre}"}" && echo "\$c"
	done
	exit
fi

_source_if() { [[ -r "\$1" ]] && source "\$1"; }
_have() { command -v "\$1" &>/dev/null; }

_log "Sourcing environment" source ~/.zshenv
EOF
)

echo -e "$SCRIPT" > "$1"
chmod +x "$1"
