#!/bin/bash
export KEG_CURRENT="${HOME}/work/zet"

if test -n "${COMP_LINE}"; then
    pre="${COMP_LINE#* }"
    COMP_LINE="ku ${pre}" ku
    exit 0
fi

cd "${KEG_CURRENT}" || exit 1
git pull &>/dev/null
ku "$@"
