#!/bin/bash

set -o nounset  # exit if undefined variable is used

cmds="e edit list ls"

edit() {
    FILE="$(which "$1")"
    if ! [[ "$(file "${FILE}")" =~ ASCII ]]; then
        exit
    fi
    $EDITOR "${FILE}"

}

list() {
    ls "${SCRIPT:-$HOME/scripts}"
}

# ---------------------- bash completion context ---------------------
set +o nounset  # exit if undefined variable is used

# add `complete -S vic vic` to bashrc or zshrc

if test -n "${COMP_LINE}"; then
    pre="${COMP_LINE##* }"
    for c in ${cmds:+${cmds} $(list)}; do
        test -z "${pre}" -o "${c}" != "${c#${pre}}" && echo "$c"
    done
    exit
fi

# ------------------------------- main -------------------------------

cmd="${1}"
test ${#} -gt 0 && shift

case "$cmd" in
ls | list) list "$@" ;;
e | edit) edit "$@" ;;
*) edit "$cmd" ;;
esac
