#!/bin/bash

set -o errexit  # exit if non-zero status code is returned
set -o nounset  # exit if undefined variable is used
set -o pipefail # exit if no-zero status code is returned in a pipeline

fzf --preview "echo {} | awk -F':' '{print \$1}' | bat -n --color=always" "$@"
