#!/bin/sh
# Author: Rob Muhlestein
# License: Apache License 2.0
# URL: https://raw.githubusercontent.com/rwxrob/dot/3533e9632c868d8383fa50b6e8fbb72c95657e6a/scripts/sshkey
set -e

typ=ed25519
confd="$HOME/.ssh"

gen() {
    name=${1:-$(date -u +%Y%m%d%H%M%S)}
    ssh-keygen -t "${typ}" -f "${confd}/id_${typ}_$name"
}

pub() {
    name="${1:-id_ed25519}"
    test -e "${confd}/${name}.pub" || return 1
    cat "${confd}/${name}.pub"
}

chpasswd() {
    name="${1:-id_ed25519}"
    test -e "${confd}/${name}.pub" || return 1
    ssh-keygen -p -f "${confd}/${name}"
}

comment() {
    name="${1:-id_ed25519}"
    test -e "${confd}/${name}.pub" || return 1
    ssh-keygen -c -f "${confd}/${name}"
}

list() {
    while read -r line; do
        line=${line##*/}
        echo "${line%.pub}"
    done <<EOF
$(ls -1 "${confd}"/*.pub)
EOF
}

# ---------------------- bash completion context ---------------------

# add `complete -S sshkey sshkey` to bashrc

if test -n "${COMP_LINE}"; then
    cmd="$(echo "${COMP_LINE}" | awk '{print $2}')"
    pre="${COMP_LINE##* }"
    case "${cmd}" in
    chpasswd | comment)
        list
        ;;
    *)
        for c in gen pub chpasswd comment list; do
            test -z "${pre}" -o "${c}" != "${c#"${pre}"}" && echo "$c"
        done
        ;;
    esac
    exit
fi

# ------------------------------- main -------------------------------

cmd="$1"
test $# -gt 0 && shift

case "$cmd" in
pub) pub "$@" ;;
gen) gen "$@" ;;
ls | list) list "$@" ;;
chpasswd) chpasswd "$@" ;;
comment) comment "$@" ;;
*) pub "$@" ;;
esac
