#!/bin/bash

set -o errexit  # exit if non-zero status code is returned
set -o pipefail # exit if no-zero status code is returned in a pipeline

cmds="list ls"

_puts() {
    case "$1" in
    todo) echo "\[ \] TODO:" ;;
    email) echo "^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$" ;;
    phone) echo "^(\+\d{1,2}\s?)?1?\-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$" ;;
    date) echo "\d{4}-\d{2}-\d{2}$" ;;
    meta-date) echo '^ {0,4}date: *\d{4}-\d{2}-\d{2}$' ;;
    meta-daily) echo '^ {0,4}.* #daily' ;;
    *)
        list
        exit 1
        ;;
    esac
}

_list() {
    echo "todo phone email date meta-date meta-daily"
}

# ---------------------- bash completion context ---------------------

# add `complete -S regex regex` to bashrc or zshrc

if test -n "${COMP_LINE}"; then
    pre="${COMP_LINE##* }"
    cmd="$(echo "${COMP_LINE}" | cut -d' ' -f 2)"
    for c in ${cmds:+${cmds} $(_list)}; do
        test -z "${pre}" -o "${c}" != "${c#${pre}}" && echo "$c"
    done
    exit
fi

# ------------------------------- main -------------------------------
cmd="${1}"
test ${#} -gt 0 && shift

case "$cmd" in
ls | list) _list "$@" ;;
*) _puts "$cmd" ;;
esac
