#!/bin/bash
#
# Generate a quickfix list that vim may consume
#
# Here is an example:
#
#   `vim <(qf grep SYMBOL)`
#   `vim <(qf modified)`

set -e

help() {
    usage
    exit 0
}

grep() {
    rg --line-number --no-heading --column "${*:-}"
}

modified() {
    git diff --name-only | awk -F: '{print $1 ":1:Modified"}'
}

usage() {
    echo "NAME"
    echo
    echo "    qf - create a quick fix list"
    echo
    echo "Synopsis"
    echo
    echo "    $(basename "$0") COMMAND"
    echo
    echo "COMMANDS"
    echo
    echo "    g|grep     - grep regular expression"
    echo "    m|modified - all modified files"
}

default() {
    help
}

########################## Command Delegation ##########################
declare subcommand="${1:-modified}"
test $# -gt 0 && shift
declare -a commands=(help usage grep modified)

######################### Tab Completion Context ########################

# add `complete -S qf qf` to bashrc

if test -n "${COMP_LINE}"; then
    pre="${COMP_LINE#* }"
    for cmd in "${commands[@]}"; do
        [[ "${cmd}" =~ ^$pre ]] && echo "${cmd}"
    done
    exit 0
fi

###################### Regular Context Delegation ######################

for i in "${commands[@]}"; do
    if [[ $i == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done
