#!/bin/sh

set -e

cmds="help usage grep modified"

help() {
    usage
    exit 0
}

grep() {
    rg --line-number --no-heading --column "$@"
}

modified() {
    git diff --name-only | awk -F: '{print $1 ":1:Modified"}'
}

usage() {
    echo "NAME"
    echo
    echo "    qf - create a quick fix list"
    echo
    echo "Synopsis"
    echo
    echo "    $(basename "$0") COMMAND"
    echo
    echo "COMMANDS"
    echo
    echo "    g|grep     - grep regular expression"
    echo "    m|modified - all modified files"
}

default() {
    help
}

# ---------------------- bash completion context ---------------------

# add `complete -S qf qf` to bashrc

if test -n "${COMP_LINE}"; then
    pre="${COMP_LINE##* }"
    for c in ${cmds:+${cmds} $(list)}; do
        test -z "${pre}" -o "${c}" != "${c#${pre}}" && echo "$c"
    done
    exit
fi

# ------------------------------- main -------------------------------

cmd="$1"
test $# -gt 0 && shift

if test -z "{cmd}"; then
    help
    exit 1
fi

case "$cmd" in
g | grep) grep "$@" ;;
m | modified) modified "$@" ;;
*) default "$@" ;;
esac
