#!/bin/bash

set -o errexit  # exit if non-zero status code is returned
set -o nounset  # exit if undefined variable is used
set -o pipefail # exit if no-zero status code is returned in a pipeline
IFS=$'\n\t'

function process() {
    echo "$0"
    head -n 1 "$0"
    # rg '^#' | xargs head -n 1
}


QUERY="$@"

rg --line-number \
   --files-with-matches \
   --no-heading \
   --smart-case \
   --glob "docs/**/README.md" \
   "$QUERY" | grep -o -E '[0-9]+'


   # "$QUERY" | xargs -o awk 'match($0, /[0-9]+/) {print substr($0, RSTART+1, RLENGTH-2)}'
