---
- name: Install ufw
  pacman:
    name: ufw
    state: present
  when: ansible_os_family == "Archlinux"

- name: Install ufw extras
  pacman:
    name: ufw-extras
    state: present
  when: ansible_os_family == "Archlinux"

- name: Start and enable ufw service
  service:
    name: ufw
    enabled: yes
    state: started

- name: Allow incoming SSH
  ufw:
    name: ssh
    direction: in
    rule: limit

- name: Reject all incoming traffic by default
  ufw:
    direction: incoming
    policy: reject

- name: Allow all outgoing traffic by default
  ufw:
    direction: outgoing
    policy: allow

- name: Set logging
  ufw:
    logging: on

- name: Turn on ufw
  ufw:
    state: enabled
  when: firewall_enabled

- name: Turn off ufw
  service:
    name: ufw.service
    state: disabled
  when: not firewall_enabled
