---
- name: Install ssh
  pacman:
    name: openssh
    state: present
  when: ansible_os_family == "Archlinux"

- name: Make SSH directory for user
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: users

- name: Set authorization key for {{ user }}
  authorized_key:
    user: "{{ username }}"
    state: present
    key: https://github.com/jlrickert.keys

- name: Copy sshd configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: /usr/sbin/sshd -t -f %s
  become: True
  notify: restart sshd

- name: Enable and start SSH Daemon
  service:
    name: sshd.service
    enabled: yes
    state: started
  when: ssh_enabled

- name: Disable and stop SSH Daemon
  service:
    name: sshd.service
    enabled: no
    state: stopped
  when: not ssh_enabled
