# Interactive zsh configuration.
case $- in
	*i*) ;;
	*) return ;;
esac

HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/zsh/history"
HISTSIZE=50000
SAVEHIST=10000
mkdir -p "${HISTFILE%/*}"

setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt share_history
setopt interactivecomments
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups

autoload -Uz compinit
compinit

alias ls='ls --color=auto 2>/dev/null || ls'
alias ll='ls -lh'
alias la='ls -lAh'
alias l='ls -lah'

bindkey -e
bindkey '^r' history-incremental-search-backward

command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"
