---
ssh: True
user: jlrickert
desktop_enabled: False
adblock_enabled: False
arch_packages:
- ansible
- at
- borg
- cloc
- cmake
- fasd
- git
- httpie
- lm_sensors
- mlocate
- pandoc
- pkgfile
- rlwrap
- syncthing
- termite-terminfo
- texlive-most
- the_silver_searcher
- tree
- ufw
- ufw
- vim
- wget
- zsh

arch_aur_packages:
- yay
- jdk

arch_display_packages:
- arandr
- dmenu
- dunst
- feh
- gnome-keyring
- gufw
- gvim
- i3
- network-manager-applet
- networkmanager
- numlockx
- pavucontrol
- pulseaudio
- unclutter
- wireshark-gtk
- xorg-xset

arch_aur_display_packages:
- i3status-rust-git
- google-chrome
- slack-desktop
