---
- name: Remove fzf package (Ubuntu)
  become: true
  ansible.builtin.apt:
      name: fzf
      state: absent
  when: ansible_distribution == "Ubuntu"

- name: Install fzf (MacOSX)
  community.general.homebrew:
      name: fzf
      state: present
  when: ansible_distribution == "MacOSX"

- name: Clean git repository
  ansible.builtin.command:
      chdir: deps/fzf
      cmd: git clean -fdx
  changed_when: false
  when: ansible_distribution != "MacOSX"

- name: Install fzf
  ansible.builtin.command:
      chdir: deps/fzf
      cmd: ./install --no-update-rc --key-bindings --completion --xdg
      creates: deps/bin/fzf
  when: ansible_distribution != "MacOSX"

- name: Install fzf dot files (MacOSX)
  ansible.builtin.command:
      chdir: deps/fzf
      cmd: /opt/homebrew/opt/fzf/install --no-update-rc --key-bindings --completion --xdg
      creates: deps/bin/fzf
  when: ansible_distribution == "MacOSX"

- name: stow fzf bin symlinks
  command:
      cmd: "stow bin --target {{ ansible_env.HOME }}/.local/bin --verbose=2"
      chdir: deps/fzf
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  when: ansible_distribution != "MacOSX"
