---
- name: Remove fzf package (Ubuntu)
  become: true
  ansible.builtin.apt:
      name: fzf
      state: absent
  when: ansible_distribution == "Ubuntu"

- name: Clean git repository
  ansible.builtin.command:
      chdir: deps/fzf
      cmd: git clean -fdx
  changed_when: false

- name: Download fzf
  ansible.builtin.command:
      chdir: deps/fzf
      cmd: ./install --no-update-rc --key-bindings --completion --xdg
      creates: deps/bin/fzf

- name: Have stow manage link
  command:
      cmd: "stow bin --target {{ ansible_env.HOME }}/.local/bin --verbose=2"
      chdir: deps/fzf
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
